name: multiscale_imaging
channels:
  - conda-forge
  - hanslovsky
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - scipy
  - javabridge
  - pytest
  - pillow
  - ipywidgets
  - imglib2-imglyb
  - pip
    - SimpleITK
    - python-bioformats
    - pyssim
    - imagej