name: multiscale
channels:
  - conda-forge
  - hanslovsky
  - simpleitk

dependencies:
  - python=3.6
  - jupyter
  - numpy
  - matplotlib
  - pandas
  - scipy
  - pytest
  - pillow
  - ipywidgets
  - imglib2-imglyb
  - SimpleITK >=1.1.0
