name: multiscale
channels:
  - conda-forge
  - simpleitk

dependencies:
  - python=3.6
  - pillow
  - requests
  - pyimagej
  - cython
  - h5py
  - jupyter
  - pandas
  - scipy
  - pytest
  - ipywidgets
  - SimpleITK >=1.1.0
  - tiffile